Add --failures-only option
instrumenta/kubeval pull request #237
Opened 2020-05-21 17:23 UTC by cnelson

👋 Would you be interested in this PR which adds a `--failures-only` option which only outputs non-PASSing results when specified. If not specified, the previous default behavior of outputting everything is left unchanged.

The motivation behind this change is that in repos with a large number of manifests it can be difficult to find the errors in the output when the majority of the manifests PASS.

❤️ Thanks for all the work on this project!

2020-06-02 14:07 UTC, DJAyth commented
Really want this as I'm going to be using kubeval as a part of my CI/CD pipelines.

2020-06-19 19:45 UTC, cnelson commented
@garethr Any interest in this feature?  feedback appreciated.  Sorry for the notification if you aren't the right person, I just see the majority of commits to master are from you.

2020-08-18 08:56 UTC, arthurlogilab commented
@cnelson we'd be interested in this too !  Maybe an improvement to your pull request would be to modify the `docs/index.md` too (where the documentation of `kubeval --help` is maintained).

2020-10-05 08:45 UTC, carlossg commented
when trying it I'm getting these `WARN`s

```
WARN - x-ingress-route.yaml containing a  (unknown) was not validated against a schema
WARN - secret.yaml containing a  (unknown) was not validated against a schema
WARN - job-template-job.yaml containing a  (unknown) was not validated against a schema
WARN - restore-job.yml containing a  (unknown) was not validated against a schema
WARN - ingress-route.yaml containing a  (unknown) was not validated against a schema
```

for `kubeval --strict -d target/templates --failures-only`

2020-10-05 08:50 UTC, carlossg commented
those files are empty objects, just containing something like

```
---
# Source: ingress-route.yaml

---
```

2020-11-18 09:06 UTC, carlossg requested changes
see above comments

2021-05-12 17:39 UTC, closed without merging

2021-05-25 11:50 UTC, calvin-j commented
Hi, would it be possible to re-open this? The `--failures-only` option is useful for our workflow and we are interested in having it included in kubeval. Currently we build a custom version of kubeval with this PR patched in, this was done with the hope that this could have been merged eventually. Thanks!

2021-05-25 13:41 UTC, carlossg commented
this PR was failing on existing objects, it would need to get fixed before merging